"""Demo feedback datasets — clearly synthetic, used for the showcase environment.

Each feedback tuple: (rating, purchase_intent, sentiment, user_name, feedback_text, suggestion)
"""
from __future__ import annotations

from typing import Dict, List, Tuple

# ----------- MedPass — 30 synthetic responses -----------
MEDPASS: List[Tuple[int, str, str, str, str, str]] = [
    (5, "definitely", "positive", "Asha P.", "An always-on QR for my medical history would be a lifesaver during travel. The AI summary of my last lab work was uncanny.", "Add multi-language support for emergency screens"),
    (5, "definitely", "positive", "Marco D.", "I struggle reading my parents' discharge papers. MedPass turning that into a plain-English summary is exactly what families need.", "Voice-read the summary aloud for elders"),
    (4, "likely", "positive", "Wendy K.", "Loved the elegant onboarding. Felt safer than a folder full of PDFs in my drawer.", "Auto-detect document type from the photo"),
    (4, "likely", "positive", "Hiro T.", "Centralizing imaging from three different clinics in one place is something I've waited a decade for.", "Allow downloading the consolidated PDF"),
    (5, "definitely", "positive", "Lena B.", "The emergency unlock code for paramedics is brilliant. Adoption will come from EMS partnerships.", "Pre-shipped sticker with the QR for fridge / wallet"),
    (4, "likely", "positive", "Daniel S.", "AI explanation of medical jargon was the killer feature for me — finally got what my cardiologist meant.", "Add a 'jargon level' slider (lay → expert)"),
    (3, "maybe", "neutral", "Priya R.", "Interesting product but I'd want SOC2 + HIPAA proof before trusting it with my records.", "Show compliance badges on the homepage"),
    (3, "maybe", "neutral", "Tom F.", "Loved the idea but felt the upload step was clunky on Android.", "Better camera capture flow on Android"),
    (4, "likely", "positive", "Ananya M.", "The travel passport mode is what sold me — perfect for digital nomads.", "Show language match for the destination automatically"),
    (5, "definitely", "positive", "Carlos V.", "My elderly mom can finally access her own records without my help. That's huge.", "Larger fonts in the elder mode"),
    (2, "unlikely", "negative", "Erin H.", "Felt the pricing wasn't clear. Wasn't sure if family sharing was extra.", "Transparent pricing page"),
    (4, "likely", "positive", "Suresh N.", "AI second-opinion module had a great UX. Felt like a careful sibling explaining a chart.", "Cite the source for each claim"),
    (5, "definitely", "positive", "Zoe A.", "Took me 4 minutes to digitize my last 5 visits — wild speed.", "Auto-classify which doctor each doc belongs to"),
    (3, "maybe", "neutral", "Idris K.", "Need offline access for areas with poor data. Otherwise great.", "Local cache + redacted-offline mode"),
    (4, "likely", "positive", "Maria L.", "The privacy explainer was thorough. Earned my trust.", "Add an 'export & delete everything' button"),
    (5, "definitely", "positive", "Olu J.", "Saved me from carrying paper forms across two hospitals.", "Add insurance card storage too"),
    (4, "likely", "positive", "Greg M.", "AI flagged a missing follow-up that my GP had skipped — that alone is worth it.", "Calendar integration for follow-ups"),
    (3, "maybe", "neutral", "Vivian C.", "Looks slick but I worry about long-term lock-in.", "Easy export to standard formats (FHIR / HL7)"),
    (2, "unlikely", "negative", "Ryan B.", "Sign-up needed too many permissions upfront. Almost dropped off.", "Progressive permissions — ask later"),
    (4, "likely", "positive", "Soo-Jin L.", "Sharing a redacted version with a new specialist saved me 20 minutes of repeating history.", "Templates for 'first visit' shares"),
    (5, "definitely", "positive", "Mehmet O.", "Smart redaction was the standout — I controlled exactly what the new doctor saw.", "Default redaction profiles"),
    (4, "likely", "positive", "Bea S.", "Beautiful UI. Felt like the Notion of healthcare.", "Dark mode for late-night reading"),
    (3, "maybe", "neutral", "Henry Q.", "Wasn't sure how it differs from my insurance app's records section.", "Crisp comparison page"),
    (4, "likely", "positive", "Lola E.", "Loved the AI prompt suggestions when I uploaded a confusing report.", "Suggest specialists based on report content"),
    (5, "definitely", "positive", "Vinay R.", "Family mode for my kids' vaccination records was perfect.", "Add growth chart visualizations"),
    (2, "unlikely", "negative", "Patrick W.", "I trust local hospitals more than a third-party app for emergencies.", "Partner explicitly with regional hospitals"),
    (4, "likely", "positive", "Eve N.", "I'd actually pay for this if it were $5/mo.", "Annual plan with a discount"),
    (5, "definitely", "positive", "Kim D.", "The QR-on-the-wallet idea is a real product, not a gimmick.", "Send a free NFC sticker on signup"),
    (3, "maybe", "neutral", "Gabriel I.", "Nice MVP but I want to see who's behind the AI summarization.", "About the model + the medical advisors page"),
    (4, "likely", "positive", "Nadia Y.", "Felt like the first health app that treated me like an adult.", "Stop the 'consult your doctor' nag on every screen"),
]

# ----------- FitGenie AI — 30 responses -----------
FITGENIE: List[Tuple[int, str, str, str, str, str]] = [
    (5, "definitely", "positive", "Jasmine W.", "A nutrition coach that knows my $40/week dining hall budget? Sign me up.", "Suggest meals from my specific cafeteria"),
    (4, "likely", "positive", "Devon O.", "The 15-minute dorm workouts hit the sweet spot.", "Add roommate-safe (quiet) workout filter"),
    (5, "definitely", "positive", "Aarav P.", "The AI noticed my exam-week stress patterns and adjusted intensity. Felt seen.", "Suggest sleep windows around my class schedule"),
    (3, "maybe", "neutral", "Tashi R.", "Looks fun but I worry about another fitness app I won't open after week 2.", "Smart push only when streak is at risk"),
    (4, "likely", "positive", "Maya B.", "Sharing streaks with my floormates created actual accountability.", "Optional weekly leaderboard for dorms"),
    (5, "definitely", "positive", "Owen Z.", "The grocery-list-from-recipes thing fits a college budget perfectly.", "Aldi vs Trader Joe's price compare"),
    (2, "unlikely", "negative", "Lia M.", "The macro tracking required too much manual input. I gave up after day 3.", "Auto-scan dining hall trays via photo"),
    (4, "likely", "positive", "Quentin S.", "AI substitutions when I'm out of ingredients were clutch.", "More vegan substitutions"),
    (3, "maybe", "neutral", "Ines K.", "Need a campus partnership angle — like meal credits.", "Integrate with campus dining APIs"),
    (5, "definitely", "positive", "Bobby H.", "Strength program adapted weekly. Felt smarter than my old PT app.", "Coach-style audio cues during sets"),
    (4, "likely", "positive", "Sofia V.", "Loved the rest-day mental health nudges.", "Add a journaling prompt"),
    (3, "maybe", "neutral", "Theo L.", "I'd pay if it were free for the first semester.", "Free term for verified .edu emails"),
    (5, "definitely", "positive", "Jada N.", "Hydration and sleep tied together in one dashboard — finally.", "Add caffeine tracking"),
    (4, "likely", "positive", "Pete F.", "Reminders timed to my class schedule, not arbitrary hours.", "Sync with Google Calendar"),
    (3, "maybe", "neutral", "Ravi C.", "Need an Apple Watch companion or I'm out.", "Watch app for quick logging"),
    (5, "definitely", "positive", "Mira E.", "The 'tonight's dinner from your fridge' feature is genius.", "Voice input for ingredients"),
    (4, "likely", "positive", "Connor B.", "AI explanation of why each food was suggested built trust quickly.", "Show the macro reasoning inline"),
    (2, "unlikely", "negative", "Ginny T.", "Felt the gamification was too kid-focused for a 22-year-old.", "Adult mode that hides badges"),
    (4, "likely", "positive", "Kenji M.", "Workouts adapted to dorm equipment, not 'imagine you have a barbell'.", "Filter by equipment available"),
    (5, "definitely", "positive", "Lucia G.", "The 'study fuel' meals before exams were a vibe.", "Coffee + snack pairing suggestions"),
    (3, "maybe", "neutral", "Sam W.", "Felt similar to MyFitnessPal premium.", "Sharpen the college-specific angle"),
    (5, "definitely", "positive", "Aiden P.", "AI knows when my finals week is and pulls back. Wild.", "Auto-pause subscription during summer"),
    (4, "likely", "positive", "Beatriz D.", "Sober-curious nudges around going-out weekends were thoughtful.", "Add mocktail recipes"),
    (3, "maybe", "neutral", "Hugo R.", "Need group challenges with my soccer team.", "Team mode with shared goals"),
    (5, "definitely", "positive", "Naya O.", "The food sensitivity adaptation worked — gluten-free options were everywhere.", "Tag known campus allergens"),
    (4, "likely", "positive", "Marek J.", "Loved the post-workout 5-min stretch routine.", "Add yoga flows"),
    (2, "unlikely", "negative", "Ophelia C.", "I'd want a real human nutritionist for credibility.", "Add Q&A with RDs as a premium tier"),
    (4, "likely", "positive", "Trent A.", "Spotify integration for workout playlists was a nice touch.", "Auto-build playlists from BPM"),
    (5, "definitely", "positive", "Halima Y.", "AI rewrote my meal plan during Ramadan automatically. Inclusive.", "Pre-built faith-based plans"),
    (4, "likely", "positive", "Eli S.", "Felt like a coach, not a tracker.", "Daily 60-second AI check-in"),
]

# ----------- FleetBrain AI — 30 responses (B2B / transit ops) -----------
FLEETBRAIN: List[Tuple[int, str, str, str, str, str]] = [
    (5, "definitely", "positive", "Ops Lead, Metro Transit", "Predictive demand shifting cut our peak-hour idle by 17% in the pilot.", "Native export to our existing AVL"),
    (4, "likely", "positive", "Fleet Manager, City Bus Co.", "Maintenance-window prediction would save weekend overtime.", "Integrate with our CMMS"),
    (5, "definitely", "positive", "Routing Analyst, RTC", "Heatmap of underserved corridors changed our planning meeting in 10 minutes.", "Animated time-of-day mode"),
    (3, "maybe", "neutral", "Director of Planning, ATU", "Promising, but procurement cycles are 9 months in our world.", "Provide a public-sector ROI calculator"),
    (4, "likely", "positive", "GM, Suburban Transit", "Real-time rerouting around incidents was the best demo I've seen.", "Push to passenger apps too"),
    (5, "definitely", "positive", "Innovation Lead, Bay Transit", "Demand forecasting on game days was eerily accurate.", "Event calendar import"),
    (2, "unlikely", "negative", "IT Director, MARTA", "Concerned about data residency for federal compliance.", "On-prem option"),
    (4, "likely", "positive", "Operations, MUNI", "AI's incident playbooks were better than what we have in print.", "Editable playbook templates"),
    (3, "maybe", "neutral", "CFO, Regional Authority", "ROI was compelling but I need a 5-year TCO model.", "TCO worksheet in the proposal"),
    (5, "definitely", "positive", "VP, ParaTransit", "Demand prediction helped paratransit dispatch reduce no-shows.", "Patient-friendly notification copy"),
    (4, "likely", "positive", "Mayor's Office, City of N.", "Equity layer showing service gaps by zip code is what we needed politically.", "Branded one-pager export"),
    (3, "maybe", "neutral", "Dispatcher Supervisor", "Drivers worry it'll be used to penalize them.", "Driver-positive framing in UI"),
    (5, "definitely", "positive", "Procurement, MTC", "Single-vendor for forecasting + route opt + analytics simplifies our stack.", "Modular pricing"),
    (4, "likely", "positive", "Director, BRT Project", "Headway management with ML was the standout.", "Visualize predicted bunching"),
    (2, "unlikely", "negative", "Union Rep", "Need clear protections that AI won't replace dispatchers.", "Public statement on workforce impact"),
    (4, "likely", "positive", "Planner, Regional MPO", "Tools work for rural fleets too. Often forgotten.", "Low-bandwidth mode"),
    (3, "maybe", "neutral", "Data Officer, Pierce Transit", "Need open API for our BI tools.", "Snowflake / BigQuery connectors"),
    (5, "definitely", "positive", "Operations Mgr, MetroRail", "Rail integration was unexpectedly slick.", "Add overhead-line predictive maintenance"),
    (4, "likely", "positive", "Sustainability Officer", "Carbon savings dashboard for our annual report was perfect.", "Sustainability badge for cities"),
    (3, "maybe", "neutral", "Cyber Lead, City IT", "Pen-test results needed before any pilot.", "Independent security audit"),
    (5, "definitely", "positive", "GM, College Town Transit", "Schedule adapted to college calendar with zero config.", "More school district presets"),
    (4, "likely", "positive", "Service Planning Lead", "Stop-level boarding prediction would let us right-size buses.", "Stop-level visual layer"),
    (2, "unlikely", "negative", "Council Member", "Worried about surveillance optics with passenger counts.", "Privacy-by-default messaging"),
    (4, "likely", "positive", "ITS Engineer", "GTFS export was straightforward.", "Live GTFS-RT publisher"),
    (5, "definitely", "positive", "Tech Lead, Demand-Response", "Demand-response dispatch was a magnitude better than what we built in-house.", "DR-specific module pricing"),
    (3, "maybe", "neutral", "Federal Grant Lead", "Need FTA grant compatibility evidence.", "Pre-filled grant boilerplate"),
    (5, "definitely", "positive", "COO, Charter Co.", "Charter operators can use this for prediction too — not just public.", "Charter mode"),
    (4, "likely", "positive", "Asset Manager", "Battery-degradation prediction for EV buses was eye-opening.", "Per-vehicle battery report"),
    (3, "maybe", "neutral", "Comms Director", "Need a citizen-facing version for transparency.", "Public dashboard light-mode"),
    (4, "likely", "positive", "Strategy Director", "First vendor to actually understand transit ops, not retrofitted DoorDash software.", "More transit case studies"),
]

# ----------- SkillSwap — 30 responses (EdTech / P2P) -----------
SKILLSWAP: List[Tuple[int, str, str, str, str, str]] = [
    (5, "definitely", "positive", "Anika P.", "Traded UX critique for Spanish lessons. Both of us got way more than a class.", "Suggest exchange ratios by skill rarity"),
    (4, "likely", "positive", "Bryan T.", "Matching algorithm is sharp — felt like Hinge for skills.", "Allow declining without awkwardness"),
    (3, "maybe", "neutral", "Cassie L.", "Worried about flaky users not showing up.", "Reputation system with no-show stats"),
    (5, "definitely", "positive", "Devang R.", "Best learning experience since college and it cost me time, not money.", "Group skill swaps (3+ people)"),
    (4, "likely", "positive", "Eliana M.", "Loved that AI matched not just skill but vibe.", "Show personality compatibility"),
    (3, "maybe", "neutral", "Faisal Q.", "Time zones blocked my matches. Need async option.", "Async swap mode with recordings"),
    (5, "definitely", "positive", "Gigi V.", "Verified-skill badge after a peer review was a key trust signal.", "Bundle badges into a portfolio link"),
    (4, "likely", "positive", "Henry C.", "Live coding session over swap was the most useful 45 min of my month.", "Built-in screenshare"),
    (2, "unlikely", "negative", "Iris D.", "Felt 'free' meant low quality. Got a flaky tutor.", "Verified Pro tier"),
    (5, "definitely", "positive", "Jordan E.", "Bartering creative for technical skills was illegal-good.", "Designer ↔ engineer focus mode"),
    (3, "maybe", "neutral", "Kaden B.", "Wanted credentials in there too — not just self-reported skills.", "LinkedIn / Coursera verification"),
    (4, "likely", "positive", "Luna O.", "AI session summary at the end was excellent for retention.", "Email the summary to both parties"),
    (5, "definitely", "positive", "Maxie J.", "Swapping languages is the best UX I've used since Duolingo.", "Add a Tandem-style chat mode"),
    (3, "maybe", "neutral", "Niko F.", "Concerned about IP if my designer shows work.", "NDA template per swap"),
    (4, "likely", "positive", "Olive H.", "Felt safer than Craigslist-style language exchanges.", "Identity verification for at-risk skills"),
    (5, "definitely", "positive", "Pria K.", "Got my first paid client via a connection on SkillSwap.", "Optional 'open to paid work' toggle"),
    (2, "unlikely", "negative", "Quinn A.", "Cancellation policy felt one-sided.", "Symmetric cancellation rules"),
    (4, "likely", "positive", "Ravi S.", "AI suggested cross-domain swaps I'd never have considered.", "Surprise-me mode"),
    (3, "maybe", "neutral", "Sana M.", "Need a mobile app for spontaneous swaps.", "iOS / Android launch ASAP"),
    (5, "definitely", "positive", "Tomas W.", "AI checks for mutual goals before matching — saves so much time.", "Pre-match prompt builder"),
    (4, "likely", "positive", "Uma B.", "Made it onto my new-grad résumé as project experience.", "Auto-generate a portfolio entry"),
    (3, "maybe", "neutral", "Vince I.", "Hard to commit weekly when I'm a parent.", "Mini-swaps (15 min) mode"),
    (5, "definitely", "positive", "Wendy K.", "Skill 'tree' view helped me realize what I should learn next.", "Show learning paths"),
    (2, "unlikely", "negative", "Xander L.", "Got matched with someone way out of my level.", "Tighter skill-band controls"),
    (4, "likely", "positive", "Yara T.", "Used by my company as a peer-learning channel.", "Team plan with workspace"),
    (3, "maybe", "neutral", "Zac N.", "Felt the 'currency' was confusing.", "Just call them hours, not credits"),
    (5, "definitely", "positive", "Esha R.", "Met three brilliant people in a month. Better than meetups.", "Curated annual cohort events"),
    (4, "likely", "positive", "Mateo P.", "Loved that the AI explained why we'd be a good swap.", "Show 'why this match' permanently"),
    (3, "maybe", "neutral", "Lior C.", "Need clearer code of conduct.", "Front-and-center community guidelines"),
    (5, "definitely", "positive", "Hina D.", "It's the platform I wish I had during my career switch.", "Career-pivot dedicated mode"),
]

FEEDBACK_DATA: Dict[str, List[Tuple[int, str, str, str, str, str]]] = {
    "medpass": MEDPASS,
    "fitgenie": FITGENIE,
    "fleetbrain": FLEETBRAIN,
    "skillswap": SKILLSWAP,
}
