"""Pre-computed demo AI insights for each project.

These are *Sample AI Analyses* clearly marked synthetic — they let the UI render
every chart, table, and module without burning real Claude calls on first deploy.
"""
from __future__ import annotations

from typing import Any, Dict


def _scaffold(
    *,
    name: str,
    val: int,
    inv: int,
    pmf: Dict[str, int],
    sentiment: Dict[str, int],
    intent: Dict[str, int],
    demand: str,
    trends: list,
    pain: list,
    love: list,
    dislike: list,
    missing: list,
    evolve: list,
    competitors: list,  # rich intel-table entries
    market_gaps: list,
    advantages: list,
    blue_ocean: list,
    business_models: list,
    revenue_models: list,
    segments: list,  # [{name, description, percent}]
    personas: list,
    swot: Dict[str, list],
    bmc: Dict[str, list],
    success: Dict[str, Any],
    pitch: list,
    investor_block: Dict[str, Any],
    report: Dict[str, Any],
) -> Dict[str, Any]:
    """Build a complete insight payload. All scores 0–100."""
    return {
        "validation_score": val,
        "demand_prediction": demand,
        "investor_readiness_score": inv,
        "sentiment_breakdown": sentiment,
        "purchase_intent_breakdown": intent,
        "trends": trends,
        "pain_points": pain,
        "competitors": [
            {"name": c["name"], "strengths": c["strengths"], "weaknesses": c["weaknesses"]}
            for c in competitors
        ],
        "business_models": business_models,
        "revenue_models": revenue_models,
        "customer_segments": segments,
        "report": report,
        "pmf": {
            **pmf,
            "what_users_love": love,
            "what_users_dislike": dislike,
            "missing_features": missing,
            "evolution_advice": evolve,
        },
        "personas": personas,
        "competitor_intel": {
            "table": competitors,
            "market_gaps": market_gaps,
            "competitive_advantages": advantages,
            "blue_ocean_opportunities": blue_ocean,
        },
        "investor": investor_block,
        "swot": swot,
        "bmc": bmc,
        "success_prediction": success,
        "pitch_deck_slides": pitch,
        "_demo_label": f"Sample AI Analysis — {name}",
    }


# ============================================================
# MedPass
# ============================================================
MEDPASS = _scaffold(
    name="MedPass",
    val=78, inv=72, demand="High",
    pmf={"pmf_score": 74, "demand_score": 82, "market_readiness_score": 68,
         "differentiation_score": 76, "scalability_score": 80},
    sentiment={"positive": 19, "neutral": 7, "negative": 4},
    intent={"definitely": 9, "likely": 12, "maybe": 6, "unlikely": 3, "no": 0},
    trends=[
        "AI-assisted medical jargon translation is the single most loved feature",
        "Emergency QR access drives instant 'aha' moments",
        "Family-mode is an under-served demand vector",
        "Compliance posture matters as a TOP-funnel filter",
        "Travel & nomad audiences are a high-intent niche",
    ],
    pain=[
        "Cumbersome Android upload flow",
        "Pricing for family sharing is opaque",
        "Up-front permissions friction at signup",
        "Trust gap vs. hospital-owned portals",
    ],
    love=[
        "Plain-English AI summaries of complex reports",
        "Emergency QR for paramedics",
        "Centralizing records across providers",
        "Smart redaction when sharing with new specialists",
    ],
    dislike=[
        "Too many permission prompts up front",
        "Lack of compliance badges before signup",
        "No offline access in low-connectivity zones",
    ],
    missing=[
        "Insurance-card storage",
        "FHIR / HL7 standard export",
        "Voice-read summaries for elders",
        "NFC sticker / wallet add-on",
    ],
    evolve=[
        "Lead with privacy and compliance proof on the homepage",
        "Build EMS partnerships to drive viral emergency use",
        "Add family-pack pricing and growth-chart visualizations",
        "Ship Android camera-first onboarding",
    ],
    competitors=[
        {"name": "Apple Health Records", "strengths": "Native integration on iOS, hospital partnerships",
         "weaknesses": "Locked to Apple, weak AI explanation layer",
         "pricing": "Free (device-bound)", "market_position": "Default for iOS users",
         "customer_sentiment": "Positive"},
        {"name": "MyChart (Epic)", "strengths": "Direct hospital data, deep US adoption",
         "weaknesses": "UX is institutional, no AI, fragmented per hospital",
         "pricing": "Free via providers", "market_position": "Provider-owned incumbent",
         "customer_sentiment": "Mixed"},
        {"name": "Doctolib", "strengths": "Booking flywheel in EU, doctor-side adoption",
         "weaknesses": "Not focused on records ownership, EU-centric",
         "pricing": "Free for patients", "market_position": "EU primary care",
         "customer_sentiment": "Positive"},
        {"name": "Google Health", "strengths": "AI infra, search distribution",
         "weaknesses": "History of pivots erodes trust, no consumer product live",
         "pricing": "—", "market_position": "Re-entering market",
         "customer_sentiment": "Mixed"},
        {"name": "Practo", "strengths": "APAC reach, booking + records",
         "weaknesses": "Brand outside India is weak, dated UI",
         "pricing": "Freemium $0–$8/mo", "market_position": "APAC leader",
         "customer_sentiment": "Mixed"},
    ],
    market_gaps=[
        "Cross-provider record consolidation with AI explanation in plain language",
        "Pre-set emergency unlock for non-tech-savvy elders",
        "Family-pack pricing with multi-profile vault",
        "Mobile-first redaction tools for sharing",
    ],
    advantages=[
        "AI jargon translator outperforms hospital portals",
        "Smart redaction is a differentiator vs Apple/MyChart",
        "Travel passport mode opens an unowned niche",
        "Family pack hits a willingness-to-pay sweet spot",
    ],
    blue_ocean=[
        "Travel-friendly digital health passport for digital nomads",
        "Caregiver-led family vaults for elder care",
        "Privacy-first AI second-opinion add-on",
        "Veterinary records extension",
    ],
    business_models=["B2C subscription", "Family-pack tiered pricing",
                     "B2B2C through employers and travel insurers",
                     "Provider partnerships (revenue share)"],
    revenue_models=["$5–$12/mo personal", "$15–$25/mo family pack",
                    "Per-employee fee for employer plans", "Optional NFC hardware bundle"],
    segments=[
        {"name": "Nomadic professionals", "description": "Travel-heavy 25–45 segment", "percent": 26},
        {"name": "Family caregivers", "description": "Adults managing parents'/children's records", "percent": 34},
        {"name": "Chronic-care patients", "description": "Multiple specialists, need consolidation", "percent": 22},
        {"name": "Privacy-first millennials", "description": "Distrust of hospital portals", "percent": 18},
    ],
    personas=[
        {"name": "Caregiver Anya", "age_range": "34–42", "occupation": "Marketing manager + caregiver",
         "income_level": "$75k–$110k",
         "goals": ["Consolidate parents' records", "Avoid repeating history at every visit"],
         "pain_points": ["Paper-form fatigue", "Records spread across 3 hospitals"],
         "buying_motivation": "Reduce caregiving cognitive load",
         "technology_usage": "Comfortable; uses Notion, Apple Health, family-shared calendars",
         "preferred_channels": ["Instagram", "Caregiver podcasts", "Family-blogs"]},
        {"name": "Nomad Diego", "age_range": "27–35", "occupation": "Remote engineer",
         "income_level": "$95k–$160k",
         "goals": ["Carry records across countries", "Avoid translation friction at clinics abroad"],
         "pain_points": ["Hospital portals don't travel", "Insurance forms in local language"],
         "buying_motivation": "Travel insurance for his medical past",
         "technology_usage": "High; uses 1Password, Linear, Notion",
         "preferred_channels": ["Twitter/X", "Nomad List", "Reddit"]},
        {"name": "Senior Margaret", "age_range": "62–74", "occupation": "Retired teacher",
         "income_level": "$45k–$70k",
         "goals": ["Be in control of her own records", "Show paramedics quickly in an emergency"],
         "pain_points": ["Apps feel hostile", "Tiny text on portals"],
         "buying_motivation": "Independence and dignity",
         "technology_usage": "Moderate; iPad + Facebook + WhatsApp",
         "preferred_channels": ["Facebook groups", "Local radio", "Doctor recommendations"]},
        {"name": "New-parent Priya", "age_range": "28–36", "occupation": "Public-school teacher",
         "income_level": "$55k–$75k",
         "goals": ["Track kids' vaccinations", "Share with pediatrician quickly"],
         "pain_points": ["Vaccine cards lost", "Multiple kid's records mixed up"],
         "buying_motivation": "Parental peace of mind",
         "technology_usage": "Moderate–high; uses Instagram, Google Calendar",
         "preferred_channels": ["Instagram", "Parenting podcasts", "Pediatrician handouts"]},
    ],
    swot={
        "strengths": ["AI summarization that's actually trusted", "Beautiful onboarding",
                      "Emergency QR is unique", "Smart redaction"],
        "weaknesses": ["Compliance proof not visible enough", "Android UX gap",
                       "Brand has zero hospital partnerships yet", "Pricing opacity"],
        "opportunities": ["Travel insurance bundles", "Caregiver SaaS upsell",
                          "Pediatrician channel", "EMS / 911 partnerships"],
        "threats": ["Hospitals locking down data", "Apple/Google encroachment",
                    "HIPAA/GDPR regulatory shifts", "Data breach reputation risk"],
    },
    bmc={
        "key_partners": ["EMS networks", "Travel insurers", "Specialty clinics",
                         "Local pediatricians"],
        "key_activities": ["AI summary R&D", "Compliance certification (HIPAA/SOC2)",
                           "Hospital data integrations"],
        "key_resources": ["Medical LLM expertise", "Encrypted vault", "Compliance team"],
        "value_proposition": ["Own your records", "Plain-English AI explanations",
                              "Travel-ready emergency access"],
        "customer_relationships": ["Concierge onboarding for families",
                                   "Self-serve for nomads", "Provider co-marketing"],
        "channels": ["App stores", "Travel insurance bundles",
                     "Caregiver communities", "Pediatrician handouts"],
        "customer_segments": ["Family caregivers", "Nomads", "Chronic-care patients",
                              "Privacy-first millennials"],
        "cost_structure": ["LLM inference", "Compliance audits", "Engineering payroll",
                           "Customer support"],
        "revenue_streams": ["Personal $9/mo", "Family $19/mo", "Employer per-seat",
                            "Hardware bundle (NFC stickers)"],
    },
    success={
        "one_year_probability": 64, "three_year_probability": 48, "five_year_probability": 36,
        "growth_drivers": ["Caregiver word-of-mouth", "EMS pilot success",
                           "Travel-insurance bundles", "Family pricing"],
        "critical_risks": ["Hospital pushback", "Compliance setback",
                           "Apple Health Records improvements", "Trust incident"],
        "market_barriers": ["Regulatory complexity by region",
                            "Provider integration lock-in", "Long sales cycles for B2B2C"],
        "explanation": "MedPass's near-term success is driven by a clear consumer pain point (records ownership + AI clarity), validated by strong qualitative feedback. The 5-year probability declines because incumbents (Apple, Epic) can replicate features once the wedge is proven, and regulatory drag scales non-linearly with geographic expansion.",
    },
    pitch=[
        {"title": "Problem", "bullets": ["Records are trapped in hospital silos",
                                          "Reports are unreadable to patients",
                                          "Emergencies expose the gap"]},
        {"title": "Solution", "bullets": ["AI-powered health passport",
                                           "Emergency QR for paramedics",
                                           "Smart redaction for sharing"]},
        {"title": "Market Opportunity", "bullets": ["$45B digital health globally",
                                                     "1.4B chronic-care patients",
                                                     "200M global nomads"]},
        {"title": "Product", "bullets": ["AI explanation layer",
                                          "Family vault", "Cross-provider import"]},
        {"title": "Competition", "bullets": ["Provider portals are clunky",
                                              "Apple Health is iOS-locked",
                                              "No one owns AI clarity layer"]},
        {"title": "Business Model", "bullets": ["B2C SaaS", "Family + Employer tiers",
                                                 "Hardware bundle"]},
        {"title": "Financial Forecast", "bullets": ["$2.5M ARR by Y2",
                                                     "65% gross margin",
                                                     "$28 CAC, $310 LTV"]},
        {"title": "Go-To-Market", "bullets": ["Caregiver communities",
                                                "Travel-insurance partnerships",
                                                "Pediatrician network"]},
        {"title": "Traction", "bullets": ["3.2k beta users",
                                            "76% W4 retention",
                                            "2 EMS pilots in motion"]},
        {"title": "Vision", "bullets": ["Own the patient layer of healthcare",
                                          "AI as a trusted second opinion",
                                          "Universal health passport"]},
    ],
    investor_block={
        "investor_readiness_score": 72, "funding_potential_score": 70,
        "market_opportunity_score": 82, "growth_potential_score": 74, "risk_score": 38,
        "why_invest": ["Clear consumer pain", "Strong qualitative validation",
                       "Differentiated AI layer", "Family + nomad expansion paths"],
        "why_reject": ["Regulatory complexity", "Hospital data access remains gated",
                       "Apple/Google can fast-follow"],
        "how_to_improve": ["Publish SOC2 + HIPAA badges", "Sign EMS LOIs",
                           "Show 90-day retention curve", "Hire a Chief Medical Officer"],
    },
    report={
        "executive_summary": "MedPass shows strong qualitative validation: 63% positive sentiment and 70% high purchase-intent across 30 sample responses. The AI summarization and emergency QR are recurring 'wow' moments, while compliance signaling and Android UX are the highest-leverage fixes. PMF score 74/100 — clear early product-market fit with a path to scale via family caregivers, nomads, and EMS partnerships. (Sample AI Analysis — Demo Data)",
        "market_risks": ["Provider lock-in on patient data",
                         "Big Tech feature parity (Apple/Google)",
                         "Regulatory tightening on AI medical use",
                         "Data breach reputational risk"],
        "opportunities": ["EMS / 911 emergency network adoption",
                          "Caregiver SaaS upsell to families",
                          "Travel-insurance bundles",
                          "Pediatrician handout channel"],
        "improvements": ["Lead with compliance badges",
                         "Android camera-first onboarding",
                         "Transparent family pricing",
                         "Progressive permissions",
                         "Specialist sharing templates"],
        "gtm_strategy": "Anchor on caregiver communities and travel-insurance bundles in months 0-9 to drive consumer pull. In parallel, sign 2-3 EMS pilots to unlock distribution and trust signals. Hit pediatricians as a passive lead channel by quarter 4. Reposition as a 'health passport for families and nomads' before broadening positioning.",
        "pricing_strategy": "Three SKUs: Personal $9/mo with annual discount, Family $19/mo (up to 6 profiles), Employer per-seat starting at $4. Offer free 30-day Family trial to convert via caregiver word-of-mouth.",
        "pitch_deck": ["Healthcare records are trapped", "MedPass is your health passport",
                       "AI translates medical jargon", "Emergency QR saves lives",
                       "Caregivers buy and recommend", "Travel-insurance bundles unlock virality",
                       "Family-pack pricing converts", "EMS pilots in motion",
                       "$2.5M ARR projection by Y2", "Vision: own the patient layer"],
    },
)


# ============================================================
# FitGenie AI (smaller block — same structure)
# ============================================================
FITGENIE = _scaffold(
    name="FitGenie AI",
    val=71, inv=64, demand="High",
    pmf={"pmf_score": 70, "demand_score": 78, "market_readiness_score": 74,
         "differentiation_score": 66, "scalability_score": 82},
    sentiment={"positive": 18, "neutral": 8, "negative": 4},
    intent={"definitely": 10, "likely": 11, "maybe": 5, "unlikely": 4, "no": 0},
    trends=["Budget-aware meal planning is the dominant ask",
            "Dorm-equipment workouts win disproportionate love",
            "AI adaptation to academic calendar resonates",
            "Quiet/roommate-safe routines under-served",
            "Mental-health crossover is a sleeper feature"],
    pain=["Manual macro entry kills retention",
          "Generic gamification feels childish for 22-year-olds",
          "Missing Apple Watch / wearable companion",
          "Sub-tier value not visible enough"],
    love=["Adaptive plans during finals week",
          "Grocery-list-from-recipes for dining halls",
          "Cross-tracking sleep + hydration",
          "AI substitutions when missing ingredients"],
    dislike=["Manual logging burden",
             "Notifications feel arbitrary",
             "Kid-style badges put off some users"],
    missing=["Apple Watch app", "Campus dining API",
             "Voice ingredient input", "Coach-style audio cues"],
    evolve=["Add photo-scan macro logging for dining halls",
            "Ship an adult-mode UI variant",
            "Partner with campus dining services",
            "Release a wearable companion in 6 months"],
    competitors=[
        {"name": "MyFitnessPal", "strengths": "Massive food DB, brand", "weaknesses": "Manual logging, generic",
         "pricing": "$19.99/mo", "market_position": "Incumbent", "customer_sentiment": "Mixed"},
        {"name": "Noom", "strengths": "Behavioral coaching, content engine",
         "weaknesses": "Weight-loss only, expensive for students",
         "pricing": "$59/mo", "market_position": "Premium mass-market",
         "customer_sentiment": "Mixed"},
        {"name": "Lifesum", "strengths": "Clean UX, EU adoption",
         "weaknesses": "Limited US distribution", "pricing": "$8.33/mo",
         "market_position": "EU consumer", "customer_sentiment": "Positive"},
        {"name": "Strong / Hevy", "strengths": "Lift-focused, fast logging",
         "weaknesses": "No nutrition layer", "pricing": "Freemium",
         "market_position": "Strength niche", "customer_sentiment": "Positive"},
        {"name": "Future", "strengths": "Human coach + tech",
         "weaknesses": "$199/mo, mass-market mismatch",
         "pricing": "$199/mo", "market_position": "Premium 1:1",
         "customer_sentiment": "Mixed"},
    ],
    market_gaps=["Student-budget aware planners",
                 "Campus dining hall integration",
                 "Quiet dorm workout library",
                 "Faith-based adaptation (Ramadan, fasting)"],
    advantages=["Dorm-first product design",
                "AI personalization beyond food logging",
                "Mental-health crossover under-claimed by competitors",
                "Cheaper than Future, smarter than MyFitnessPal"],
    blue_ocean=["Greek-life team challenges",
                "Roommate-collab mode",
                "Campus-dining API marketplace",
                "Athlete-tier for D-III + club sports"],
    business_models=["Freemium B2C", ".edu free term + upsell",
                     "Campus B2B2C licensing", "Wearables bundle"],
    revenue_models=["$4.99/mo student tier", "$9.99/mo standard",
                    "$2/student per term for campuses",
                    "Affiliate revenue (groceries, supplements)"],
    segments=[
        {"name": "Budget-aware students", "description": "$30–$60/wk food budget", "percent": 38},
        {"name": "Student athletes", "description": "Club / D-III competitive", "percent": 22},
        {"name": "Faith-observant students", "description": "Ramadan, halal/kosher", "percent": 14},
        {"name": "Recovery / mental-health-aware", "description": "Stress-aware routines", "percent": 26},
    ],
    personas=[
        {"name": "Sophomore Sam", "age_range": "19–21", "occupation": "Undeclared major",
         "income_level": "$0–$8k", "goals": ["Stay healthy without effort",
                                              "Eat well on a $45/wk budget"],
         "pain_points": ["Dining hall food rotation",
                          "Workout time around lab schedule"],
         "buying_motivation": "Convenience > price for stress weeks",
         "technology_usage": "Native phone user, Spotify, Snapchat",
         "preferred_channels": ["TikTok", "Snapchat", "Campus posters"]},
        {"name": "Club-Athlete Asha", "age_range": "20–23", "occupation": "Engineering + club soccer",
         "income_level": "$5k–$15k (side gigs)",
         "goals": ["Performance nutrition", "Recovery on a budget"],
         "pain_points": ["No team-level tools", "Generic apps don't know her sport"],
         "buying_motivation": "Edge in performance",
         "technology_usage": "Wearable user, Strava",
         "preferred_channels": ["Instagram", "Strava", "Team group-chats"]},
        {"name": "Grad Student Theo", "age_range": "23–27", "occupation": "PhD candidate",
         "income_level": "$22k–$30k stipend",
         "goals": ["Avoid grad-school weight gain", "Manage stress"],
         "pain_points": ["Late-night research wrecks routine",
                          "Coffee + cortisol spiral"],
         "buying_motivation": "Stay in control during a long degree",
         "technology_usage": "High; Notion, Obsidian, Calendar",
         "preferred_channels": ["Reddit", "YouTube", "Discord servers"]},
    ],
    swot={
        "strengths": ["Student-aware AI", "Budget-first design", "Dorm-equipment library",
                      "Adaptive to academic calendar"],
        "weaknesses": ["Brand new vs incumbents", "No wearable yet",
                       "Manual logging friction", "Campus partnerships absent"],
        "opportunities": ["Campus dining integration", "Wearables companion",
                          "Greek-life network effects", "Mental-health crossover"],
        "threats": ["MyFitnessPal price drop", "Apple/Google fitness rings expansion",
                    "Burnout / churn risk in student app category", "Privacy regs on minors (incl. dual-enrolled HS)"],
    },
    bmc={
        "key_partners": ["Campus dining services", "Wearable OEMs",
                         "Student associations", "Grocery affiliates"],
        "key_activities": ["AI personalization", "Content production",
                           "Campus partnership BD"],
        "key_resources": ["Recipe DB", "AI model", "Campus integration toolkit"],
        "value_proposition": ["Coach, not tracker", "Budget-aware",
                              "Adapts to your schedule"],
        "customer_relationships": ["Community", "Peer leaderboards",
                                   "Email check-ins"],
        "channels": ["TikTok organic", "Campus reps", ".edu email campaigns"],
        "customer_segments": ["Budget-aware students", "Club athletes",
                              "Faith-observant", "Grad students"],
        "cost_structure": ["AI inference", "Content creators",
                           "Campus rep stipends", "Engineering"],
        "revenue_streams": ["Student tier", "Standard tier",
                            "Campus licensing", "Affiliate revenue"],
    },
    success={
        "one_year_probability": 58, "three_year_probability": 42, "five_year_probability": 30,
        "growth_drivers": ["Campus-rep flywheel", "Wearable companion",
                           "Faith / niche modes", "Cross-promo with Spotify"],
        "critical_risks": ["High churn post-graduation",
                           "Incumbent price cuts",
                           "Dining-hall integration delays"],
        "market_barriers": ["Procurement cycles at universities",
                            "Saturation of fitness apps",
                            "Wearable platform fees"],
        "explanation": "FitGenie's wedge is sharp (students, dorm-aware) but the category is brutally competitive at scale. Year 1 success is driven by viral campus pilots; long-term success depends on retaining users post-graduation and converting alumni — a known weak point for student-first products.",
    },
    pitch=[
        {"title": "Problem", "bullets": ["Generic fitness apps assume a barbell and a meal-prepped fridge",
                                          "Students need adaptive, budget-aware coaching"]},
        {"title": "Solution", "bullets": ["AI coach trained on dorm reality",
                                           "Plans adapt to the academic calendar"]},
        {"title": "Market Opportunity", "bullets": ["20M US college students",
                                                     "$22B fitness app market",
                                                     "$8B campus dining"]},
        {"title": "Product", "bullets": ["Dorm-equipment workouts",
                                          "Dining-hall meal plans",
                                          "Cross-tracking + stress mode"]},
        {"title": "Competition", "bullets": ["MyFitnessPal: manual & generic",
                                              "Future: $199/mo",
                                              "We are the AI coach for $5/mo"]},
        {"title": "Business Model", "bullets": ["Freemium + .edu",
                                                 "Campus licensing", "Affiliate"]},
        {"title": "Financial Forecast", "bullets": ["1.2M registered Y2",
                                                     "8% paid conversion",
                                                     "$5.6M ARR run-rate"]},
        {"title": "Go-To-Market", "bullets": ["Campus ambassadors",
                                                "TikTok creators",
                                                "Greek life pilots"]},
        {"title": "Traction", "bullets": ["2 campus pilots booked",
                                            "31% W2 retention in beta",
                                            "1.4k waitlist"]},
        {"title": "Vision", "bullets": ["Be the AI coach a student keeps after graduation",
                                          "Bridge from campus to first-job wellness"]},
    ],
    investor_block={
        "investor_readiness_score": 64, "funding_potential_score": 62,
        "market_opportunity_score": 78, "growth_potential_score": 70, "risk_score": 46,
        "why_invest": ["Sharp wedge", "Strong qualitative validation",
                       "Clear cost-aware UX moat", "Multi-segment expansion"],
        "why_reject": ["Crowded category",
                       "Student retention risk after graduation",
                       "Wearable / Apple Health pressure"],
        "how_to_improve": ["Sign 5 campus pilots",
                           "Show post-graduation retention plan",
                           "Ship wearable companion",
                           "Hire a fitness brand advisor"],
    },
    report={
        "executive_summary": "FitGenie AI lands a strong student-shaped product wedge. 60% positive sentiment, 70% high-intent, PMF 70/100. The biggest leverage points are wearable companion shipping, campus-dining integrations, and an adult-mode UI to retain post-graduation. The validation score (71) reflects high love among target users tempered by category saturation. (Sample AI Analysis — Demo Data)",
        "market_risks": ["Incumbent price cuts", "Post-grad churn",
                         "Apple Fitness expansion", "TikTok-trend reliance"],
        "opportunities": ["Campus B2B2C", "Wearable companion",
                          "Faith-based / niche modes", "Spotify integration"],
        "improvements": ["Photo-scan dining tray logging", "Adult-mode UI",
                         "Voice ingredient input",
                         "Audio coach during sets",
                         "Transparent .edu pricing"],
        "gtm_strategy": "Lean on a 50-school ambassador program in Year 1, with founders flying to top universities. Layer in dining-hall API integrations as a unique distribution wedge by month 6. Use TikTok creator partnerships to fill the funnel and campus posters for trust.",
        "pricing_strategy": "Tiered: Free with limits, $4.99/mo student (.edu), $9.99/mo standard, $2/student/term for campus deals. Free summer to fight churn.",
        "pitch_deck": ["Generic apps ignore students", "FitGenie is the AI coach that knows your dorm",
                       "Adaptive plans for finals week", "Campus pilots booked",
                       "MyFitnessPal can't follow into our wedge", "Affordable, sticky, viral",
                       "Wearable companion next", "$5.6M ARR projection",
                       "Founder is a 2x edtech operator", "Vision: from campus to lifelong wellness"],
    },
)


# ============================================================
# FleetBrain AI (B2B / transit)
# ============================================================
FLEETBRAIN = _scaffold(
    name="FleetBrain AI",
    val=82, inv=80, demand="High",
    pmf={"pmf_score": 80, "demand_score": 84, "market_readiness_score": 76,
         "differentiation_score": 82, "scalability_score": 72},
    sentiment={"positive": 18, "neutral": 8, "negative": 4},
    intent={"definitely": 12, "likely": 10, "maybe": 5, "unlikely": 3, "no": 0},
    trends=["Public-sector procurement cycles dominate the deal timeline",
            "Equity / accessibility dashboards are required, not optional",
            "Demand-response and paratransit are the highest-pain wedges",
            "AI playbooks beat printed SOPs immediately on usage",
            "On-prem / data-residency questions arise on every demo"],
    pain=["Long procurement cycles (9–18 months)",
          "Driver-union concerns about AI scoring",
          "Data residency and SOC2 demands",
          "Federal grant compatibility unclear"],
    love=["Predictive demand forecasting on event days",
          "Heatmaps of underserved corridors",
          "AI incident playbooks",
          "Charter mode and rural-fleet support"],
    dislike=["Concerns about driver surveillance",
             "Lack of low-bandwidth mode initially",
             "No native CMMS integration yet"],
    missing=["FTA grant boilerplate", "On-prem deployment option",
             "Public-citizen-facing dashboard", "Native CMMS connector"],
    evolve=["Lead with equity dashboard for political wins",
            "Build a driver-positive narrative and union liaison program",
            "Ship on-prem option for federal contracts",
            "Open API + GTFS-RT publishing as standard"],
    competitors=[
        {"name": "Optibus", "strengths": "Strong scheduling + crew", "weaknesses": "Limited AI for demand",
         "pricing": "Enterprise $$$", "market_position": "Top-tier scheduling",
         "customer_sentiment": "Positive"},
        {"name": "Swiftly", "strengths": "GTFS realtime, on-time perf",
         "weaknesses": "Lighter on predictive + planning",
         "pricing": "Enterprise $$", "market_position": "Real-time leader",
         "customer_sentiment": "Positive"},
        {"name": "Via", "strengths": "DR + microtransit operator + software",
         "weaknesses": "Conflicts being both vendor and operator",
         "pricing": "Per-rider/operator", "market_position": "Microtransit",
         "customer_sentiment": "Mixed"},
        {"name": "Remix (Via)", "strengths": "Planning visualization",
         "weaknesses": "Now part of Via, integration uncertainty",
         "pricing": "Enterprise", "market_position": "Planning legacy",
         "customer_sentiment": "Mixed"},
        {"name": "Stantec / IBI", "strengths": "Consulting brand", "weaknesses": "Not software-led",
         "pricing": "Consulting $$$$", "market_position": "Consulting",
         "customer_sentiment": "Mixed"},
    ],
    market_gaps=["AI-first demand forecasting across mode (bus + DR + rail)",
                 "Equity / accessibility dashboards out of the box",
                 "Procurement-ready on-prem deployments",
                 "Rural and small-system support"],
    advantages=["Multi-modal AI not retrofitted from ride-hailing",
                "Equity layer baked-in",
                "Driver-positive framing",
                "Federal-grant ready proposal kit"],
    blue_ocean=["Charter and tour-bus operators",
                "School bus districts",
                "Tribal transit agencies",
                "Inter-city / Greyhound-tier"],
    business_models=["Per-vehicle SaaS",
                     "Per-trip variable for DR",
                     "Implementation services",
                     "Federal-grant co-applications"],
    revenue_models=["$60–$120/vehicle/mo", "$0.05/DR trip",
                    "$80k–$300k implementations",
                    "Co-applied federal grant fees"],
    segments=[
        {"name": "Mid-size transit agencies", "description": "100–500 vehicles", "percent": 36},
        {"name": "Demand-response operators", "description": "Paratransit & microtransit", "percent": 28},
        {"name": "Charter / tour", "description": "Charter operators expanding software", "percent": 16},
        {"name": "Rural & tribal", "description": "Underserved by enterprise vendors", "percent": 20},
    ],
    personas=[
        {"name": "Director Dana", "age_range": "44–58", "occupation": "Director of Planning",
         "income_level": "$110k–$160k",
         "goals": ["Win the FTA grant", "Show equity gains to council"],
         "pain_points": ["Procurement timelines", "Legacy AVL contracts"],
         "buying_motivation": "Politically-defensible modernization",
         "technology_usage": "Moderate; Excel + GIS",
         "preferred_channels": ["APTA conferences", "Industry newsletters",
                                "Government Technology"]},
        {"name": "Ops Manager Omar", "age_range": "35–48", "occupation": "Operations Mgr",
         "income_level": "$85k–$120k",
         "goals": ["Cut peak idle", "Reduce overtime",
                   "Avoid bunching"],
         "pain_points": ["Tools fragmented across 3 vendors",
                          "Driver pushback on tech"],
         "buying_motivation": "Smoother daily ops, fewer fires",
         "technology_usage": "Comfortable; CAD/AVL daily user",
         "preferred_channels": ["LinkedIn", "Vendor demos", "Peer agency calls"]},
        {"name": "IT Director Inez", "age_range": "40–55", "occupation": "Public-sector IT",
         "income_level": "$100k–$145k",
         "goals": ["Stay compliant", "Avoid breach headlines"],
         "pain_points": ["Vendor lock-in", "Data residency"],
         "buying_motivation": "Risk reduction + auditability",
         "technology_usage": "High; cloud-cautious",
         "preferred_channels": ["GovTech", "StateScoop", "NASCIO"]},
    ],
    swot={
        "strengths": ["Multi-modal AI", "Equity dashboard out-of-box",
                      "Driver-positive framing", "Grant-ready proposals"],
        "weaknesses": ["No on-prem option yet", "Limited CMMS integrations",
                       "Brand awareness vs incumbents", "Sales cycle is long"],
        "opportunities": ["FTA grants tailwind", "Tribal & rural underserved",
                          "Charter expansion", "Carbon dashboards trend"],
        "threats": ["Optibus / Swiftly fast follow",
                    "Procurement freeze",
                    "Political pushback on driver scoring",
                    "Data breach reputational risk"],
    },
    bmc={
        "key_partners": ["APTA", "Federal Transit Administration",
                         "AVL/CAD vendors", "GTFS data partners"],
        "key_activities": ["Multi-modal AI", "Implementation",
                           "Grant boilerplate authoring"],
        "key_resources": ["Transit data lake", "Field implementations team",
                          "Public-sector compliance"],
        "value_proposition": ["AI-first multi-modal ops",
                              "Equity dashboard ready",
                              "Grant-aligned procurement"],
        "customer_relationships": ["High-touch onboarding",
                                   "Agency-positive change mgmt",
                                   "Public-sector account team"],
        "channels": ["APTA events", "Direct sales",
                     "Federal grant partnerships",
                     "Consulting referrals"],
        "customer_segments": ["Mid-size agencies", "DR operators",
                              "Charter & tour", "Rural/tribal"],
        "cost_structure": ["Implementation labor", "AI training data",
                           "Compliance & security", "Sales overhead"],
        "revenue_streams": ["Per-vehicle SaaS", "DR per-trip",
                            "Implementation fees", "Grant co-application"],
    },
    success={
        "one_year_probability": 70, "three_year_probability": 60, "five_year_probability": 50,
        "growth_drivers": ["FTA modernization grants",
                           "Multi-modal land-and-expand",
                           "Charter/rural wedges",
                           "Equity-mandated procurements"],
        "critical_risks": ["Federal funding shifts",
                           "Optibus aggressive bundling",
                           "Pilot-to-paid conversion lag"],
        "market_barriers": ["Long procurement cycles",
                            "Public-sector security demands",
                            "Union politics"],
        "explanation": "FleetBrain operates in a deep, defensible vertical where AI-native incumbents are still rare. Public-sector deal velocity is slow but stickiness is exceptional. With 2-3 lighthouse pilots, the next 3 years compound through reference selling — making the 3y and 5y probabilities more correlated than in B2C plays.",
    },
    pitch=[
        {"title": "Problem", "bullets": ["Transit ops run on fragmented stacks",
                                          "Demand changes faster than schedules",
                                          "Equity gaps go unmeasured"]},
        {"title": "Solution", "bullets": ["AI-first multi-modal ops",
                                           "Equity dashboard out of box",
                                           "Driver-positive incident playbooks"]},
        {"title": "Market Opportunity", "bullets": ["$12B US transit software",
                                                     "5,800+ US agencies",
                                                     "FTA modernization tailwind"]},
        {"title": "Product", "bullets": ["Demand forecasting",
                                          "Equity layer", "AI playbooks"]},
        {"title": "Competition", "bullets": ["Optibus: scheduling",
                                              "Swiftly: realtime",
                                              "We unify both with AI"]},
        {"title": "Business Model", "bullets": ["Per-vehicle SaaS",
                                                 "DR per-trip",
                                                 "Implementations + grants"]},
        {"title": "Financial Forecast", "bullets": ["$6M ARR Y2",
                                                     "120% NDR target",
                                                     "75% gross margin"]},
        {"title": "Go-To-Market", "bullets": ["APTA conference flywheel",
                                                "Lighthouse pilots",
                                                "Federal grant co-app"]},
        {"title": "Traction", "bullets": ["3 lighthouse LOIs",
                                            "1 paid pilot live",
                                            "FTA grant submitted"]},
        {"title": "Vision", "bullets": ["AI operating system for public transit",
                                          "Equitable mobility for every city"]},
    ],
    investor_block={
        "investor_readiness_score": 80, "funding_potential_score": 76,
        "market_opportunity_score": 84, "growth_potential_score": 72, "risk_score": 32,
        "why_invest": ["Defensible vertical", "Strong qualitative signal",
                       "Tailwind from federal grants",
                       "Multi-modal expansion paths"],
        "why_reject": ["Long procurement cycles",
                       "Incumbent fast follow",
                       "Mission-critical reliability risk"],
        "how_to_improve": ["Land paid lighthouse",
                           "Publish SOC2 + StateRAMP",
                           "Sign 2 charter partners",
                           "Recruit GovTech advisor"],
    },
    report={
        "executive_summary": "FleetBrain AI demonstrates the strongest validation in the demo cohort (82/100), driven by deep operator pain and unique multi-modal AI positioning. 60% positive sentiment, 73% high-intent. Risks are procurement speed, not product–market fit. PMF 80/100. Funding-readiness 80. Public sector deals will compound through reference selling. (Sample AI Analysis — Demo Data)",
        "market_risks": ["Federal funding shifts",
                         "Optibus / Swiftly aggressive bundling",
                         "Mission-critical reliability incidents",
                         "Union-led political pushback"],
        "opportunities": ["FTA modernization grants",
                          "Tribal & rural under-served",
                          "Charter / tour expansion",
                          "Equity-mandated procurements"],
        "improvements": ["Ship on-prem deployment",
                         "Native CMMS connector",
                         "Public citizen dashboard",
                         "Driver-positive framing"],
        "gtm_strategy": "Anchor on 3 lighthouse mid-size agencies in Year 1, supported by APTA presence and federal grant co-applications. Add charter and tribal wedges in Year 2 to bypass slow public procurement. Use a high-touch implementation team and reference selling.",
        "pricing_strategy": "Per-vehicle SaaS ($60–$120 depending on tier) plus $0.05/DR trip plus implementations ($80k–$300k). Multi-year discount + co-applied grant fees to reduce CFO friction.",
        "pitch_deck": ["Transit ops are fragmented",
                       "FleetBrain unifies them with AI", "Equity layer baked in",
                       "Driver-positive framing", "Lighthouse pilots live",
                       "Federal grants are tailwind", "$6M ARR target",
                       "Multi-modal expansion", "Defensible vertical",
                       "Vision: AI OS for public transit"],
    },
)


# ============================================================
# SkillSwap (consumer EdTech / P2P)
# ============================================================
SKILLSWAP = _scaffold(
    name="SkillSwap",
    val=68, inv=58, demand="Medium",
    pmf={"pmf_score": 66, "demand_score": 70, "market_readiness_score": 64,
         "differentiation_score": 72, "scalability_score": 64},
    sentiment={"positive": 16, "neutral": 9, "negative": 5},
    intent={"definitely": 8, "likely": 11, "maybe": 6, "unlikely": 4, "no": 1},
    trends=["AI matching for skill + vibe is the standout",
            "Reputation / no-show stats are essential trust",
            "Async + mobile are gating features",
            "Career-pivot users are a high-intent segment",
            "Team / B2B mode under-claimed"],
    pain=["Flaky users and no-shows",
          "Time-zone misalignment",
          "Currency naming is confusing",
          "IP / NDA concerns from designers"],
    love=["Cross-domain swap suggestions",
          "AI session summaries",
          "Verified-skill badges after peer review",
          "Mobile-friendly swap experience"],
    dislike=["Free-tier quality variance",
             "Confusing 'credits' nomenclature",
             "Asymmetric cancellation policy"],
    missing=["Mobile apps", "Async / recorded swap mode",
             "Team workspace", "Mini-swaps (15-min)"],
    evolve=["Ship a Pro tier and team workspaces",
            "Rename 'credits' to 'hours' for clarity",
            "Add reputation analytics public to all parties",
            "Launch async + mini-swap modes"],
    competitors=[
        {"name": "Tandem (lang)", "strengths": "Strong language pair UX",
         "weaknesses": "Single-skill (language)", "pricing": "Freemium",
         "market_position": "Language exchange", "customer_sentiment": "Positive"},
        {"name": "Preply", "strengths": "Trusted brand, paid tutors",
         "weaknesses": "Not peer-to-peer, expensive",
         "pricing": "$10–$30/hr", "market_position": "Paid tutoring",
         "customer_sentiment": "Positive"},
        {"name": "Skillshare", "strengths": "Content library",
         "weaknesses": "One-way, no live exchange",
         "pricing": "$14/mo", "market_position": "Content subscription",
         "customer_sentiment": "Mixed"},
        {"name": "MeetUp", "strengths": "Community + IRL",
         "weaknesses": "Generic groups, no AI matching",
         "pricing": "Freemium", "market_position": "Community legacy",
         "customer_sentiment": "Mixed"},
        {"name": "Lunchclub", "strengths": "AI matching for networking",
         "weaknesses": "Networking only, not skill exchange",
         "pricing": "Free", "market_position": "Networking matchmaker",
         "customer_sentiment": "Mixed"},
    ],
    market_gaps=["AI matching across skill + style + goals",
                 "Career-pivot specific cohort",
                 "Team-mode for peer learning at companies",
                 "Async / recorded skill swaps"],
    advantages=["AI 'why this match' is unique",
                "Cross-domain swap suggestions",
                "Peer-verified portfolio badges",
                "Designed by ex-Lunchclub / Tandem talent"],
    blue_ocean=["Career-pivot cohort programs",
                "Company team peer-learning",
                "Verified-portfolio export for freelancers",
                "Mini-swaps (commute-friendly 15-min sessions)"],
    business_models=["Freemium B2C",
                     "Pro tier subscription",
                     "Team workspace SaaS",
                     "Verified-portfolio export upsell"],
    revenue_models=["$8/mo Pro", "$12/seat/mo team",
                    "Cohort program fees", "Verified export $19"],
    segments=[
        {"name": "Career-pivoters", "description": "Mid-career, switching skill stacks", "percent": 30},
        {"name": "Creators & designers", "description": "Trading skill for client work", "percent": 22},
        {"name": "Language learners", "description": "Conversational practice", "percent": 26},
        {"name": "New grads", "description": "Building portfolio + network", "percent": 22},
    ],
    personas=[
        {"name": "Pivoter Priya", "age_range": "28–38", "occupation": "Career-switching marketer",
         "income_level": "$70k–$95k",
         "goals": ["Learn PM skills", "Build a network in new field"],
         "pain_points": ["Coding bootcamps too expensive", "Lonely transition"],
         "buying_motivation": "Lower-cost, higher-trust learning",
         "technology_usage": "High; Notion + LinkedIn power user",
         "preferred_channels": ["LinkedIn", "Lenny's Newsletter", "Reforge"]},
        {"name": "Creator Caleb", "age_range": "24–32", "occupation": "Freelance designer",
         "income_level": "$45k–$75k",
         "goals": ["Trade design for engineering help",
                   "Build a verified portfolio"],
         "pain_points": ["Time and IP risk", "Client-finding fatigue"],
         "buying_motivation": "Get unstuck without paying",
         "technology_usage": "High; Figma, X/Twitter",
         "preferred_channels": ["X/Twitter", "Layers", "Designer communities"]},
        {"name": "Polyglot Pari", "age_range": "21–30", "occupation": "Master's student",
         "income_level": "$0–$20k",
         "goals": ["Practice conversational French",
                   "Trade Hindi for French"],
         "pain_points": ["Tandem is language-only",
                          "Tutors are too expensive"],
         "buying_motivation": "Real conversation, free",
         "technology_usage": "Native mobile, TikTok",
         "preferred_channels": ["Instagram", "Discord", "TikTok"]},
    ],
    swot={
        "strengths": ["AI matching is genuinely loved",
                      "Cross-domain swap UX is novel",
                      "Network-effects potential",
                      "Career-pivot is a hot segment"],
        "weaknesses": ["No mobile app yet",
                       "Reputation system early",
                       "Cancellation policy lop-sided",
                       "Pricing nomenclature confusing"],
        "opportunities": ["Career-pivot cohorts",
                          "Team workspaces",
                          "Verified portfolio export",
                          "Async / recorded swaps"],
        "threats": ["Tandem expansion",
                    "Preply price wars",
                    "LinkedIn skill exchange features",
                    "Burnout / churn at low-engagement segments"],
    },
    bmc={
        "key_partners": ["Career coaches", "Portfolio platforms",
                         "Tooling (Figma, Notion)", "Cohort program operators"],
        "key_activities": ["AI matching",
                           "Reputation & trust",
                           "Community programs"],
        "key_resources": ["AI matching model", "Reputation graph",
                          "Community team"],
        "value_proposition": ["Trade skills, not money",
                              "AI 'why this match'",
                              "Verified-skill portfolio"],
        "customer_relationships": ["Community-led",
                                   "Founder DMs in early cohorts",
                                   "Pro tier concierge"],
        "channels": ["X/Twitter", "Career-pivot newsletters",
                     "Cohort program partners"],
        "customer_segments": ["Career-pivoters", "Creators & designers",
                              "Language learners", "New grads"],
        "cost_structure": ["AI inference",
                           "Trust & safety",
                           "Community ops",
                           "Engineering"],
        "revenue_streams": ["Pro subscription",
                            "Team workspaces",
                            "Cohort programs",
                            "Portfolio exports"],
    },
    success={
        "one_year_probability": 52, "three_year_probability": 38, "five_year_probability": 26,
        "growth_drivers": ["Career-pivot cohort virality",
                           "Team workspaces upsell",
                           "Verified portfolio export",
                           "Async swap mode"],
        "critical_risks": ["LinkedIn entering",
                           "Trust incident",
                           "Marketplace cold-start"],
        "market_barriers": ["Two-sided marketplace ignition",
                            "Reputation graph trust",
                            "Mobile app delay"],
        "explanation": "SkillSwap shows real love but operates in a fragmented EdTech corner with two-sided marketplace dynamics. Year 1 momentum is plausible via career-pivot cohorts; longer-term success depends on building a defensible reputation graph faster than incumbents can copy the AI matching layer.",
    },
    pitch=[
        {"title": "Problem", "bullets": ["Learning skills costs money",
                                          "Tutors are expensive",
                                          "Online courses are lonely"]},
        {"title": "Solution", "bullets": ["Trade your skill for another's",
                                           "AI matches skill + vibe",
                                           "Verified portfolio for freelancers"]},
        {"title": "Market Opportunity", "bullets": ["1B+ professionals globally",
                                                     "$350B education spend",
                                                     "Career-pivot tailwind"]},
        {"title": "Product", "bullets": ["AI matching",
                                          "Verified swap reviews",
                                          "Mobile + async"]},
        {"title": "Competition", "bullets": ["Preply: paid",
                                              "Tandem: language-only",
                                              "We are the AI peer-exchange"]},
        {"title": "Business Model", "bullets": ["Freemium B2C",
                                                 "Pro + Team tiers",
                                                 "Cohort programs"]},
        {"title": "Financial Forecast", "bullets": ["$3.8M ARR Y2",
                                                     "6% paid conversion",
                                                     "70% gross margin"]},
        {"title": "Go-To-Market", "bullets": ["Career-pivot newsletters",
                                                "Designer Twitter",
                                                "University career centers"]},
        {"title": "Traction", "bullets": ["1.2k early users",
                                            "62% W4 retention",
                                            "8 cohort partnerships"]},
        {"title": "Vision", "bullets": ["The peer-learning OS for adults",
                                          "Skills as currency"]},
    ],
    investor_block={
        "investor_readiness_score": 58, "funding_potential_score": 56,
        "market_opportunity_score": 70, "growth_potential_score": 60, "risk_score": 50,
        "why_invest": ["Differentiated AI matching",
                       "Strong qualitative love",
                       "Career-pivot tailwind",
                       "Network-effects potential"],
        "why_reject": ["Marketplace cold-start risk",
                       "Reputation graph immature",
                       "LinkedIn risk"],
        "how_to_improve": ["Ship mobile apps",
                           "Launch a paid cohort program",
                           "Publish reputation analytics",
                           "Sign a portfolio platform partnership"],
    },
    report={
        "executive_summary": "SkillSwap shows promising peer-learning love (53% positive sentiment, 63% high intent) and a novel AI matching wedge. PMF score 66/100 reflects strong unique value but two-sided marketplace ignition risk. Ship mobile + reputation analytics + cohort programs in Year 1 to compound. (Sample AI Analysis — Demo Data)",
        "market_risks": ["LinkedIn entering",
                         "Marketplace cold-start fatigue",
                         "Trust incident",
                         "Preply price wars"],
        "opportunities": ["Career-pivot cohorts",
                          "Team workspaces",
                          "Verified-portfolio export",
                          "Async swap mode"],
        "improvements": ["Ship mobile apps",
                         "Rename credits to hours",
                         "Symmetric cancellation policy",
                         "Reputation analytics in profile",
                         "Mini-swap mode"],
        "gtm_strategy": "Anchor on career-pivot cohorts (paid programs) and designer/creator Twitter for inbound. Layer in team workspaces in Y2. Avoid expensive paid acquisition early; build a public reputation graph that makes SkillSwap inherently shareable.",
        "pricing_strategy": "Free with limits, $8/mo Pro, $12/seat/mo team, $19 verified-portfolio export. Cohort programs $199 per 6-week cohort.",
        "pitch_deck": ["Skills as currency",
                       "AI matches you with your perfect swap partner",
                       "Verified portfolio after each swap",
                       "Career-pivot cohorts are the wedge",
                       "Team workspaces unlock B2B", "Network-effects flywheel",
                       "$3.8M ARR projection", "Mobile + async next",
                       "LinkedIn is the existential risk", "Vision: peer-learning OS"],
    },
)

INSIGHTS = {
    "medpass": MEDPASS,
    "fitgenie": FITGENIE,
    "fleetbrain": FLEETBRAIN,
    "skillswap": SKILLSWAP,
}
